name: MFA Sweep

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
      password:
        description: 'Password'
        required: true

jobs:
  mfa_sweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: pwsh
        run: |
          apt-get -y update 
          apt-get -y install wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          apt-get -y update
          apt-get install -y powershell
      - name: mfa Sweep
        id: sweep
        working-directory: ${{ github.workspace }}
        env:
          USERNAME: ${{ github.event.inputs.username }}
          PASSWORD: ${{ github.event.inputs.password }}
        run: |
          Import-Module ./MFASweep.ps1
          $results = Invoke-GraphAPIAuth -Username $env:USERNAME -Password $env:PASSWORD

          echo "results = $results" >> $env:GITHUB_OUTPUT
        shell: pwsh